normal = [
    ["ysy", "22aeff"],
    ["jhr", "9200ff"],
    ["ljw", "fff800"],
    ["kcy", "98f21d"],
    ["kyy", "d80d76"],
    ["ksm", "ff7fa4"],
    ["knk", "729ba1"],
    ["gyb", "ffe3e2"],
    ["ked", "ffc931"],
    ["sdh", "fb98dc"],
    ["ktn", "ffe000"],
    ["kyj", "5873fd"],
    ["hnt", "ff953f"],
    ["psh", "1222b5"]
]
sl = [
    ["ysy", "22aeff"],
    ["jhr", "9200ff"],
    ["ljw", "fff800"],
    ["kcy", "9bff0f"],
    ["kyy", "ff0084"],
    ["ksm", "ff7fa4"],
    ["knk", "729ba1"],
    ["gyb", "ffe3e2"],
    ["ked", "ffc931"],
    ["sdh", "ff94dd"],
    ["ktn", "ffe000"],
    ["kyj", "5773ff"],
    ["hnt", "ff953f"],
    ["psh", "0014c7"]
]
